apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .resourceId }}-remote"
  labels:
    hyperfleet.io/cluster-id: "{{ .resourceId }}"
  annotations:
    hyperfleet.io/generation: "{{ .generation }}"
